# Generated by Django 5.2 on 2025-07-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens',
            field=models.IntegerField(default=0),
        ),
    ]
